"""Quests Table

Revision ID: ce0eb75d17ac
Revises: 
Create Date: 2020-02-27 17:17:49.914192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0eb75d17ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_quest_description'), 'quest', ['description'], unique=True)
    op.create_index(op.f('ix_quest_name'), 'quest', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_name'), table_name='quest')
    op.drop_index(op.f('ix_quest_description'), table_name='quest')
    op.drop_table('quest')
    # ### end Alembic commands ###
